config/routes.rb
Rails.application.routes.draw do
  resources :flights
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check
  get "home", to: "home#home"
  root to: "flights#search"
  get "flights", to: "flights#flights"
  get "search", to: "flights#search"
  #post "/", to: "bookings#new", :as => 'bookings'
  #patch "booking.:id", to: "bookings#update"
  #get "booking", to: "bookings#create"


  resources :bookings

  #post "booking", to: "booking#create"
  #resources :bookings
  # Defines the root path route ("/")
  # root "posts#index"
  #testtestetsetstsetset
end

app/models/airport.rb
class Airport < ApplicationRecord
    has_many :departure_airports, class_name: 'Flight' , foreign_key: 'arrival_airport_id'
    has_many :arrival_airports, class_name: 'Flight', foreign_key: 'departure_airport_id'

    def departure_airport_code
       airport_code 
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
    belongs_to :flight, class_name: 'Flight'

    has_many :passengers, class_name: 'Passenger', foreign_key: 'booking_id'

    accepts_nested_attributes_for :passengers

end

app/models/flight.rb
class Flight < ApplicationRecord
    belongs_to :departure_airport, class_name: 'Airport'
    belongs_to :arrival_airport, class_name: 'Airport'

    has_many :flights, class_name: 'Flight' , foreign_key: 'flight_id'

    has_many :bookings

    delegate :departure_airport_code, to: :departure_airport
    

    def flight_time_formatted
        flight_time.strftime("%F %R")
    end
end

app/models/passenger.rb
class Passenger < ApplicationRecord
    has_many :flights, class_name: 'Flight', foreign_key: 'flight_id'
    has_many :bookings, class_name: 'Booking', foreign_key: 'booking_id'
 
 
 
end
 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[ show edit update destroy ]

  def index 
    @bookings = Booking.all
  end
    
  def new
    @booking = Booking.new(booking_params)
    @flight = @booking.flight
    params[:passenger_number].to_i.times {@booking.passengers.build}
    @flight_id = Flight.find(params[:booking][:id]).id
  end

  def create
    @booking = Booking.new(booking_params)
    respond_to do |format|
      if @booking.save
        format.html { redirect_to booking_url(@booking), notice: "Booking was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  def update
  end


  def edit
  end

  def destroy
  end

  private
  
  def set_booking
    @booking = Booking.find_by(id: params[:id])
  end

  def booking_params
      params.require(:booking).permit(:flight_id, :passengers_attributes => [:passenger_name, :passenger_email])
  end

end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :set_flight, only: %i[ show edit update destroy ]

  # GET /flights or /flights.json
  def index
    @flights = Flight.all
  end

  # GET /flights/1 or /flights/1.json
  def show
   redirect_to booking_path
  end

  # GET /flights/new
  def new
    @flight = Flight.new
  end

  # GET /flights/1/edit
  def edit
  end

  def search
    @results = Flight.all
    if params[:search]
      @results = @results.where("departure_airport_id like ?", 
      "%#{params[:search]}%")
    end
    if params[:arr_airport_search]
      @results = @results.where("arrival_airport_id like ?", 
      "%#{params[:arr_airport_search]}%")
      end
    if params[:dep_time_search]
      @results = @results.where("flight_time like ?", 
      "%#{params[:dep_time_search]}%")
    end
 end

  # POST /flights or /flights.json
  def create
    @flight = Flight.new(flight_params)

    respond_to do |format|
      if @flight.save
        format.html { redirect_to flight_url(@flight), notice: "Flight was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flights/1 or /flights/1.json
  def update
    respond_to do |format|
      if @flight.update(flight_params)
        format.html { redirect_to flight_url(@flight), notice: "Flight was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flights/1 or /flights/1.json
  def destroy
    @flight.destroy!

    respond_to do |format|
      format.html { redirect_to flights_url, notice: "Flight was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flight
      @flight = Flight.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def flight_params
      params.require(:flight).permit(:arrival_airport_id, :departure_airport_id, :flight_time, :flight_duration)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def home
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/booking/booking.html.haml
%h1 Enter Booking Details
= form_with model: @booking do |form|
  = form.label :flight_id, "Enter Flight ID:", style: "display: block"
  = form.number_field :flight_id
  %br/
  %br/
  = form.label :passenger_name, "Enter Your Name:", style: "display: block"
  = form.text_field :passenger_name
  %br/
  %br/
  = form.label :passenger_email, "Enter Your Email", style: "display: block"
  = form.text_field :passenger_email
  %br/
  %br/
  = form.label :no_passenger, "Enter Number of Passengers:", style: "display: block"
  = form.number_field :no_passenger
  %br/
  %br/
  = form.submit
  %br/
  %br/
  = @booking

app/views/bookings/_booking.html.haml
= "Congratulations #{booking.passengers.first.passenger_name}, your flight has now been booked"
%br
%h3 Flight Details
= "Booking ID: #{booking.id}"
%br
= "Flight ID: #{booking.flight_id}"
%br
= "Departure Airport: #{booking.flight.departure_airport.airport_code}"
%br
= "Arrival Airport: #{booking.flight.arrival_airport.airport_code}"
%br
= "Flight Time: #{booking.flight.flight_time}"
%br
= "Flight Duration: #{booking.flight.flight_duration} minutes"
%br
%br
%h3 Passenger Details
= "There are #{booking.passengers.count} passengers"
%br
- booking.passengers.each do |passenger|
    %br
    = "Passenger ID: #{passenger.id}"
    %br
    = "Passenger Name: #{passenger.passenger_name}"
    %br
    = "Passenger Email: #{passenger.passenger_email}"
    %br
    %br
%h1 Enjoy your Flight!

app/views/bookings/_form.html.haml
%br
%h2 Here are Your Selected Flight Details!
%br
= "Flight ID: #{Flight.find(params[:booking][:id]).id}"
%br
%br
= "Departure Airport: #{Flight.find(params[:booking][:id]).departure_airport.airport_code}"
%br
%br
= "Arrival Airport: #{Flight.find(params[:booking][:id]).arrival_airport.airport_code}"
%br
%br
= "Departure Time: #{Flight.find(params[:booking][:id]).flight_time}"
%br
%br
= "Duration: #{Flight.find(params[:booking][:id]).flight_duration} minutes"
%br
%br
%h2 Enter Passenger Information
%br
= "Number of Passengers: #{params[:passenger_number]}"
%br
%br

= form_for @booking do |f|
    = f.hidden_field(:flight_id, value: @flight_id)
    = f.fields_for :passengers do |passenger_form|    
        = passenger_form.label "Passenger Name: "
        = passenger_form.text_field :passenger_name
        %br
        = passenger_form.label "Passenger Email: "
        = passenger_form.text_field :passenger_email
        %br
        %br
    = f.submit

app/views/bookings/index.html.haml
%p{:style => "color: green"}= notice
%h1 Bookings
#bookings
  - @bookings.each do |booking|
    = render booking

app/views/bookings/new.html.haml
= render 'form'

app/views/bookings/show.html.haml
%p{:style => "color: green"}= notice

= render @booking

app/views/flights/_flight.html.haml
%div{:id => "#{dom_id flight}"}
  %p
    %strong Dep airport:
    = flight.dep_airport
  %p
    %strong Arr airport:
    = flight.arr_airport
  %p
    %strong Dep time:
    = flight.dep_time
  %p
    %strong Duration:
    = flight.duration

app/views/flights/_form.html.haml
= form_with(model: flight) do |form|
  - if flight.errors.any?
    %div{:style => "color: red"}
      %h2
        = pluralize(flight.errors.count, "error")
        prohibited this flight from being saved:
      %ul
        - flight.errors.each do |error|
          %li= error.full_message
  %div
    = form.label :dep_airport, style: "display: block"
    = form.select :dep_airport, ["AAR", "BWT", "HDS", "JAS", "LAO"]
  %div
    = form.label :arr_airport, style: "display: block"
    = form.select :arr_airport, ["AAR", "BWT", "HDS", "JAS", "LAO"]
  %div
    = form.label :dep_time, style: "display: block"
    = form.datetime_field :dep_time
  %div
    = form.label :duration_in_minutes, style: "display: block"
    = form.number_field :duration, step: 5
  %div
    = form.submit

app/views/flights/edit.html.haml
%h1 Editing flight
= render "form", flight: @flight
%br/
%div
  = link_to "Show this flight", @flight
  |
  \#{link_to "Back to flights", flights_path}

app/views/flights/index.html.haml
%p{:style => "color: green"}= notice
%h1 Flights
#flights
  - @flights.each do |flight|
    = render flight
    %p
      = link_to "Show this flight", flight
= link_to "New flight", new_flight_path

app/views/flights/new.html.haml
%h1 New flight
= render "form", flight: @flight
%br/
%div
  = link_to "Back to flights", flights_path

app/views/flights/search.html.haml
- no_of_pass =  params[:passenger_number].presence || 1
 
= form_tag(search_path, :method => "get") do
  = select_tag :search, options_from_collection_for_select(@results, "departure_airport_id", "departure_airport_id"), {:prompt => 'Departure Airport'}
  = select_tag :arr_airport_search, options_from_collection_for_select(@results, "arrival_airport_id", "arrival_airport_id"), {:prompt => 'Arrival Airport'}
  = select_tag :dep_time_search, options_from_collection_for_select(@results, :flight_time_formatted, :flight_time_formatted), {:prompt => 'Departure Time'}
  = select_tag :passenger_number, options_for_select(['', '1', '2', '3', '4']), {prompt: 'Number of Passengers'}

  = button_tag "Search"
%br
%h3 Search Results
- @results.each do |result|
  = "FLIGHT ID:         #{result.id}"
  %br/
  = "Departure Airport: #{result.departure_airport.airport_code}"
  %br/
  = "Arrival Airport:   #{result.arrival_airport.airport_code}"
  %br/
  = "Departure Time:    #{result.flight_time}"
  %br/
  = "Duration:          #{result.flight_duration} minutes"
  %br/
  %br/
  = "-----------------------------------------------------"
  %br/
  

= form_for '', url: new_booking_path, method: :get, html: {id: 'new_booking_form' } do |form|
  = form.label :Select_flight, style: "display: block"
  = form.hidden_field(:passenger_number, value: no_of_pass)
  = collection_radio_buttons(:booking, :id, @results, :id, :departure_airport_code)
  = form.submit "Select Flight"


-# = form_with(model: @result) do |form|
-#   = form.label :Select_flight, style: "display: block"
-#   = collection_radio_buttons(:booking, :id, @results, :id, :departure_airport_code)

-#   = form.submit "Select Flight"
-#   %br/
  

app/views/flights/show.html.haml
%p{:style => "color: green"}= notice
= render @flight
%div
  = link_to "Edit this flight", edit_flight_path(@flight)
  |
  \#{link_to "Back to flights", flights_path}
  
  \#{button_to "Destroy this flight", @flight, method: :delete}

app/views/home/home.html.haml
%h1
  Andrew Hunter Flight-booker Project 
%br
%h2
  Use Instructions:
%br
%h3 
  Select Search in the navigation bar to begin.
  %br 
  %br
  Select departure, arrival, time, and number of passengers and ensure to click Search to refine the displayed flights.
  %br
  %br 
  Selecting number of passengers and clicking search is crucial to ensuring the nested forms feature is displayed.
  %br 
  %br 
  Input passenger details, and press book.
  %br 
  %br 
  View your boooking information. 

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FlightBooker
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    %link{:crossorigin => "anonymous", :href => "https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css", :integrity => "sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC", :rel => "stylesheet"}/
    %script{:crossorigin => "anonymous", :integrity => "sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM", :src => "https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"}
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  %body
    %nav.navbar.navbar-expand-lg.navbar-light.bg-light
      .container-fluid
        %a.navbar-brand{:href => "/home"} Flight Booker
        %button.navbar-toggler{"aria-controls" => "navbarNavDropdown", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarNavDropdown", "data-bs-toggle" => "collapse", :type => "button"}
          %span.navbar-toggler-icon
        #navbarNavDropdown.collapse.navbar-collapse
          %ul.navbar-nav
            %li.nav-item
              %a.nav-link.active{"aria-current" => "page", :href => "/home"} Home
            %li.nav-item
              %a.nav-link{:href => "/flights"} 
            %li.nav-item
              %a.nav-link{:href => "/"} Search
    = yield